apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lost-port-loadbalancer
  annotations:
#    nginx.ingress.kubernetes.io/rewrite-target: /lost-port
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/affinity-mode: "persistent"
    nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
spec:
#  defaultBackend:
#    service:
#      name: lost-port-service
#      port:
#        number: 8080
  ingressClassName: nginx
  rules:
    - host: internal.tjhonghuang.com
      http:
        paths:
          - path: /lost-port
            pathType: Prefix
            backend:
              service:
                name: lost-port-service
                port:
                  number: 8080
                
